import { Component, OnInit } from '@angular/core';
import { AngularFirestoreCollection, AngularFirestore } from 'angularfire2/firestore';
import { Observable } from 'rxjs';
import { AuthService } from 'src/app/service/auth.service';
export interface Item { nombre: string; url: string; usuario: string; }
export interface Part { nombre: string; correo: string; password: string; }

@Component({
  selector: 'app-archivos',
  templateUrl: './archivos.component.html',
  styleUrls: ['./archivos.component.css']
})
export class ArchivosComponent implements OnInit {
  email: string;
  private itemsCollection: AngularFirestoreCollection<Item>;
  items: Observable<Item[]>;
  
  participantes = [
    {nombre:'Ubaldo Cortés',correo:'delfos85@hotmail.com',password:'123456'},  
    {nombre:'Ubaldo Alvarez',correo:'nickjunior12@yahoo.com.mx',password:'123456'},  
    {nombre:'Mariana Estrada González',correo:'eglezmariana96@outlook.com',password:'03PFCMX01100'},
    {nombre:'Claudia Coello de Portugal Millán',correo:'claudiacoellomillan@gmail.com',password:'03PFCES36101'},
    {nombre:'David Efrain Vega Montoya',correo:'devm.o@hotmail.com',password:'03PFCMX14102'},
    {nombre:'Miguel Ruiz Velasco',correo:'miguel.ruve@gmail.com',password:'03PFCMX01103'},
    {nombre:'José Armando Román Mireles',correo:'arq.armando.roman@gmail.com',password:'03PFCMX01104'},
    {nombre:'Mirel Perales Gutiérrez',correo:'mirel.perales.gt@gmail.com',password:'03PFCMX01105'},
    {nombre:'David Meza Sandoval ',correo:'david.mx.93@gmail.com',password:'03PFCMX01106'},
    {nombre:'Víctor Uriel Álvarez Casillas',correo:'vuroalvarez07@gmail.com',password:'03PFCMX14108'},
    {nombre:'Adrián Galindo González',correo:'ag.adrian@outlook.es',password:'03PFCMX09110'},
    {nombre:'Edgar Fabián Martínez Castillo',correo:'cammar.arq@gmail.com',password:'03PFCMX01111'},
    {nombre:'Diego Fernando Oscos Rueda',correo:'oscosrueda@gmail.com',password:'03PFCMX01112'},
    {nombre:'Gerson Guízar Félix',correo:'gerson.guizar@gmail.com',password:'03PFCMX01113'},
    {nombre:'Eduardo Maldonado Rivera',correo:'eduardo.maldonado.arq@gmail.com',password:'03PFCMX01115'},
    {nombre:'Aleida Rahel Perez Merkel',correo:'merkelaleida@gmail.com',password:'03PFCMX01116'},
    {nombre:'Mario Elías Nava Diaz',correo:'marioe.nvdz@gmail.com',password:'03PFCMX14119'},
    {nombre:'Fernando Israel Leal Leyte',correo:'f.leal@volevaarquitectos.com',password:'03PFCMX01120'},
    {nombre:'Edith Marcela Urias Barrera',correo:'emub26@gmail.com',password:'03PFCMX04122'},
    {nombre:'Sofía Arzate Velasco',correo:'sofarvel82@gmail.com',password:'03PFCMX01123'},
    {nombre:'Marco Antonio del Arco Bravo ',correo:'geniuscubearquitectos@gmail.com',password:'03PFCMX22124'},
    {nombre:'Jorge Arturo López Bustamante ',correo:'jorgebustamante_arq@hotmail.com',password:'03PFCMX01125'},
    {nombre:'Jesus Alfonso Canché Pech',correo:'alfonsohad@outlook.com',password:'03PFCMX17126'},
    {nombre:'Paulina Parra Ledesma',correo:'paulinaparral@gmail.com',password:'03PFCMX22127'},
    {nombre:'Diego Regalado Gil',correo:'a01702946@itesm.mx',password:'03PFCMX06128'},
    {nombre:'Leonel Vidal Hermenegildo Barranco',correo:'leonel.hermenegildo.barranco@gmail.com',password:'03PFCMX02129'},
    {nombre:'Carlos Alberto Fuentes Alcibar',correo:'carlosfual46@gmail.com',password:'03PFCMX01130'},
    {nombre:'Juan Manuel Portillo Ramírez ',correo:'manoloprt@gmail.com',password:'03PFCMX01131'},
    {nombre:'Rafael Omar Júarez Raygoza ',correo:'rafaeljraygoza@hotmail.com',password:'03PFCMX01132'},
    {nombre:'Verónica Joselin Muñoz Mendoza',correo:'vero.jmm@outlook.com',password:'03PFCMX06133'},
    {nombre:'Esteban Estrella Guillén',correo:'estebanestrellag@gmail.com',password:'03PFCMX16134'},
    {nombre:'José Emmauel Martínez Reyes',correo:'ibnemma@hotmail.com',password:'03PFCMX01136'},
    {nombre:'María Agali Miranda Ramírez',correo:'agalimiranda@hotmail.com',password:'03PFCMX28137'},
    {nombre:'José Luis Arellanos Cisneros',correo:'jlarci19199009@gmail.com',password:'03PFCMX03138'},
    {nombre:'Eliud Ricardo Millán González ',correo:'udarqez@gmail.com',password:'03PFCMX02139'},
    {nombre:'Juan Agustin Rivera Gonzalez de Cossio',correo:'juanagustinrivera@gmail.com',password:'03PFCMX01140'},
    {nombre:'Francisco Javier Méndez Rodríguez',correo:'paco.mendez@hibridotaller.com',password:'03PFCMX27141'},
    {nombre:'Santiago Borda Orellana',correo:'borda.santiago.95@gmail.com',password:'03PFCMX03142'},
    {nombre:'Sergio Abraham Trinidad Flores',correo:'asatf.93@gmail.com',password:'03PFCMX01143'},
    {nombre:'Eduardo Moreno Rivera',correo:'edumrivera@gmail.com',password:'03PFCES36144'},
    {nombre:'Miriam Yohana Castro Cabanillas ',correo:'lh070606@gmail.com',password:'03PFCMX11145'},
    {nombre:'Francisco José Bilbao Soto ',correo:'fjbilbao@hotmail.com',password:'03PFCMX14146'},
    {nombre:'Cesar Octavio Gama Hernández',correo:'octaviogama46@gmail.com',password:'03PFCMX18147'},
    {nombre:'José Daniel Jiménez Bravo ',correo:'danieljbravo38@gmail.com',password:'03PFCMX02149'},
    {nombre:'Constantino Martell Castañeda ',correo:'arq.zh@hotmail.com',password:'03PFCMX27152'},
    {nombre:'Jorge Luis Hernández Zanjuampa',correo:'jlhernanz08@gmail.com',password:'03PFCMX06153'},
    {nombre:'Alonso Figueroa Camacho',correo:'arq.alonsofigueroa@gmail.com',password:'03PFCMX14154'},
    {nombre:'José Hugo Alvarado Arvizu',correo:'helmoo_gouh@hotmail.com',password:'03PFCMX22155'},
    {nombre:'Emmanuel Villaseñor Ramírez',correo:'emmanuel.vila@hotmail.com',password:'03PFCMX14157'},
    {nombre:'José Luis Gutiérrez Ruvalcaba',correo:'jluis.859814@gmail.com',password:'03PFCMX05158'},
    {nombre:'Mitzi Lozada Chiñas',correo:'mitzi.lozadach@gmail.com',password:'03PFCMX28159'},
    {nombre:'Leopoldo Orendain Ruiz Escoto',correo:'polo.ore@mogtaller.com',password:'03PFCMX14160'},
    {nombre:'Brian Armando Razo Aguilera ',correo:'bri.razo57@gmail.com',password:'03PFCMX02162'},
    {nombre:'Jorge Aurelio Pantaleon Arazo',correo:'jorgepantaleon18@gmail.com',password:'03PFCMX02163'},
    {nombre:'Adriana Castro Bernal',correo:'adrianacb207@gmail.com',password:'03PFCMX01164'},
    {nombre:'Pablo Antonio Ziga Barajas',correo:'pabzigbar@gmail.com',password:'03PFCMX01166'},
    {nombre:'Luis Enrique Rodriguez Wilde',correo:'rwilde.arq@gmail.com',password:'03PFCMX01167'},
    {nombre:'Jordi Domenech Borquez',correo:'jorborquez@gmail.com',password:'03PFCMX01168'},
    {nombre:'Juan Enrique Arguijo Hoyo',correo:'jenrique.arguijo@gmail.com',password:'03PFCMX01169'},
    {nombre:'Enya Carolina Martínez Torres',correo:'enyamartz@gmail.com',password:'03PFCMX09170'},
    {nombre:'Cynthia Lorena Montero Alvarado',correo:'loren.lmst@gmail.com',password:'03PFCMX14171'},
    {nombre:'Gustavo Parra Castañeda',correo:'gusparraca@gmail.com',password:'03PFCMX24172'},
    {nombre:'Carlos Roberto González Páez',correo:'robeertogonzalez@gmail.com',password:'03PFCMX13173'},
    {nombre:'Manuel Reyes Castro',correo:'reyes.manuel@live.com.mx',password:'03PFCMX23175'},
    {nombre:'Jaime Zamora Salgado ',correo:'zamora.sjaime1@gmail.com',password:'03PFCMX06176'},
    {nombre:'Carla Patricia Leiva Castañeda',correo:'carlaaalc@gmail.com',password:'03PFCMX07177'},
    {nombre:'Mauricio Humberto Macías Guzmán',correo:'mauriciomgh@hotmail.com',password:'03PFCMX02178'},
    {nombre:'Aileen Abril Barrera Novella',correo:'abrilobarrera@gmail.com',password:'03PFCMX01179'},
    {nombre:'Francisco Garrido Roca',correo:'fragarroc@gmail.com',password:'03PFCES36180'},
    {nombre:'Christopher Martínez Ontiveros',correo:'christ.mar.ont@gmail.com',password:'03PFCMX02181'},
    {nombre:'Juan Carlos Miguel Bautista ',correo:'arqmiguelbautista@gmail.com',password:'03PFCMX02182'},
    {nombre:'Santiago Martínez Hernández ',correo:'zanz_95@hotmail.com',password:'03PFCMX06184'},
    {nombre:'Silvia Midori Pérez García ',correo:'midori_29@outlook.es',password:'03PFCMX01185'},
    {nombre:'Enrico Eugenio Hernández Cervantes',correo:'enricohc@gmail.com',password:'03PFCMX22186'},
    {nombre:'Alberto Macías Cornejo',correo:'albert.102129@gmail.com',password:'03PFCMX09188'},
    {nombre:'Orlando Quitano Cuauhtle',correo:'orlando.quitano@gmail.com',password:'03PFCMX26189'},
    {nombre:'Ricardo Vela Ramírez',correo:'a00571713@itesm.mx',password:'03PFCMX22190'},
    {nombre:'Marco Garcini Munguía',correo:'mikegarcini@hotmail.com',password:'03PFCMX06191'},
    {nombre:'José Carlos Reyes Ayala',correo:'estudio.arq.rj@gmail.com',password:'03PFCMX01192'},
    {nombre:'Manuel Alejandro Medina Guzmán',correo:'manu.20.mmm@gmail.com',password:'03PFCMX01193'},
    {nombre:'Israel Alejandro Muñiz Rodríguez ',correo:'alejantrophy@outlook.es',password:'03PFCMX09194'},
    {nombre:'Jaime Eduardo Lango Delgado ',correo:'jaime_arq00@hotmail.com',password:'03PFCMX26195'},
    {nombre:'Daniela Montserrath Romano Zarazua ',correo:'monch-95@hotmail.com',password:'03PFCMX06196'},
    {nombre:'Gabriel Alfaro Fregoso',correo:'alfarofregoso@gmail.com',password:'03PFCMX14197'},
    {nombre:'Nanely Scanda Cortés Medina ',correo:'nelycortes17@hotmail.com',password:'03PFCMX02198'},
    {nombre:'Adolfo Valentino Corona Alfaro',correo:'adolfocorona7@hotmail.com',password:'03PFCMX14199'},
    {nombre:'Sergio Israel Mejía Piña',correo:'sergioisraelmejia@gmail.com',password:'03PFCMX01201'},
    {nombre:'Bruno Jiménez Rodríguez',correo:'arqbrunojimenez@gmail.com',password:'03PFCMX01202'},
    {nombre:'Juan Carlos Garduño Rivera ',correo:'arq.gardunorivera@gmail.com',password:'03PFCMX11203'},
    {nombre:'Miguel Domínguez Díaz de León',correo:'doguez-srt92@live.com.mx',password:'03PFCMX06204'},
    {nombre:'Asael Alfredo Martínez Ramírez',correo:'asamr6@gmail.com',password:'03PFCMX01205'},
    {nombre:'Héctor Adrián Batres Parás',correo:'hbatres92@hotmail.com',password:'03PFCMX06206'},
    {nombre:'Sebastian Spiess Castilla',correo:'sebastian.spiesscastilla@gmail.com',password:'03PFCMX06207'},
    {nombre:'Daniel Sesma Hernández',correo:'sesma707@gmail.com',password:'03PFCMX01208'},
    {nombre:'Christian Cisneros Camacho',correo:'cu_91_ccc@hotmail.com',password:'03PFCMX01209'},
    {nombre:'Carlos Alonso Elizondo Valladares',correo:'celizondo@arqueodigma.mx',password:'03PFCMX14210'},
    {nombre:'Juan Carlos Scandella Martínez Fresneda ',correo:'smf.architecture@gmail.com',password:'03PFCES36211'},
    {nombre:'Alejandro Talavera Hernández',correo:'arquitectohdz05@gmail.com',password:'03PFCMX01212'},
    {nombre:'Karla Erika Escalona Castillejos',correo:'arquitecturasostenible@tallersenkali.com',password:'03PFCMX01213'},
    {nombre:'Daniela Andrea Chánez Reyes',correo:'danielachanez@outlook.com',password:'03PFCMX01214'},
    {nombre:'Luis Alejandro Pérez Martínez',correo:'luis.perez91@outlook.com',password:'03PFCMX05215'},
    {nombre:'Dalia Elizabeth Martínez Rivera',correo:'martinez.dalia9@gmail.com',password:'03PFCMX01216'},
    {nombre:'Roberto Gallegos Barrera',correo:'gllgs.roberto@gmail.com',password:'03PFCMX06217'},
    {nombre:'José Luis De los Reyes Díaz de León',correo:'joseluisdlr99@gmail.com',password:'03PFCMX06218'},
    {nombre:'Azael Velázquez Estrada',correo:'azael.ve@hotmail.com',password:'03PFCMX06219'},
    {nombre:'Vicente Jaimes Sánchez',correo:'vickjames78@gmail.com',password:'03PFCMX11221'},
    {nombre:'Jesús Uriel Cervantes Varela',correo:'varela.jc.uriel@gmail.com',password:'03PFCMX02222'},
    {nombre:'Daniel Martín Gurza',correo:'danielmartin_g@hotmail.com',password:'03PFCMX03223'},
    {nombre:'Cintia Viridiana Martínez Pascual',correo:'arq.cintiamtz@gmail.com',password:'03PFCMX28224'},
    {nombre:'Albert Agustín Jimenez Lobato',correo:'arq.albert.lobato@live.com.mx',password:'03PFCMX05225'},
    {nombre:'Isaac Solis Rosas',correo:'isaacsolis.ro@gmail.com',password:'03PFCMX14227'},
    {nombre:'Maher Abisai Sarracino Guemez',correo:'mager.sarracino@gmail.com',password:'03PFCMX20228'},
    {nombre:'Fernando Alonso Tuero ',correo:'fatuero@gmail.com',password:'03PFCES36229'},
    {nombre:'Francisco Blázquez García',correo:'francisco.j.blazquez.garcia@gmail.com',password:'03PFCES36230'},
    {nombre:'Arianna Isabel Chi Prudencio ',correo:'arianna.prudencio@gmail.com',password:'03PFCMX20231'},
    {nombre:'Mary Karen Gutiérrez Aguilar ',correo:'gagrafmaj@gmail.com',password:'03PFCMX01232'},
    {nombre:'Karla Mejía Valdez',correo:'karlamejiav@gmail.com',password:'03PFCMX03233'},
    {nombre:'Manuel García Millán',correo:'magami.arq@gmail.com',password:'03PFCMX30234'},
    {nombre:'Luis Gerardo Flores Flores',correo:'gerarq.do@outlook.com',password:'03PFCMX03235'},
    {nombre:'Monserrat Cortés Macías',correo:'cortes.monserratt@gmail.com',password:'03PFCMX14236'},
    {nombre:'Verónica Fernanda Ocampo Liceaga',correo:'veronicaocampo1910@gmail.com',password:'03PFCMX01237'},
    {nombre:'Francisco Javier Chávez Muñiz',correo:'javierc.arquitecto@gmail.com',password:'03PFCMX14238'},
    {nombre:'Martha Irma Guillen Ibarra',correo:'margibarra@hotmail.com',password:'03PFCMX22239'},
    {nombre:'Karen Estefanía Manjarrez Guevara',correo:'karenn04@icloud.com',password:'03PFCMX28240'},
    {nombre:'Ian Brian Arévalo Rodríguez',correo:'estudiobari.proyectos@gmail.com',password:'03PFCMX13241'},
    {nombre:'Gabriela Hernández López',correo:'ghernandez19@alumnos.uaq.mx',password:'03PFCMX06242'},
    {nombre:'Renato Gianfranco Soto Ledesma',correo:'renatosoto52@gmail.com',password:'03PFCPE36243'},
    {nombre:'Víctor Iván García Camela',correo:'garcia.camela.victor.ivan@gmail.com',password:'03PFCMX01244'},
    {nombre:'José Juan Muñoz Gómez',correo:'arq_jmunoz@outlook.com',password:'03PFCMX09245'},
    {nombre:'Jhonatan Blancas Mejía ',correo:'arq.blancas@gmail.com',password:'03PFCMX01246'},
    {nombre:'Federico Hernández Barrón',correo:'make.herba@gmail.com',password:'03PFCMX23247'},
    {nombre:'Alberto Gisholt Tayabas',correo:'agisholt@gmail.com',password:'03PFCMX01248'},
    {nombre:'Elba Alejandra Kaplun Castelo',correo:'ale.kaplun@gmail.com',password:'03PFCMX06249'},
    {nombre:'Alberto Sosa Huergo',correo:'arq.terra1@gmail.com',password:'03PFCMX02250'},
    {nombre:'Jorge Alfonso Sedeño Reyes',correo:'jasr_jorge19@hotmail.com',password:'03PFCMX14251'},
    {nombre:'Fernanda Ruiz Pratellesi',correo:'ruiz.fernanda29@gmail.com',password:'03PFCMX06252'},
    {nombre:'Fernando Sampietro',correo:'f.sampietro.c@gmail.com',password:'03PFCMX01253'},
    {nombre:'Eduardo Metodio Antonino',correo:'eduardometodio08@gmail.com',password:'03PFCMX06254'},
    {nombre:'Erick Guajardo López',correo:'ekguajardo@gmail.com',password:'03PFCMX03255'},
    {nombre:'Karla Citlalli Contreras Marín',correo:'citlacm@hotmail.com',password:'03PFCMX01256'},
    {nombre:'Erick Alexis López de la Cruz',correo:'alexisldlck@gmail.com',password:'03PFCMX26257'},
    {nombre:'Susana Rojas Saviñón',correo:'susana@estudioome.com',password:'03PFCMX01258'},
    {nombre:'Francisco Xavier Quezada Figueroa',correo:'proyectos.nudo.arq@gmail.com',password:'03PFCMX01259'},
    {nombre:'Juan Adolfo de la Cruz Valdéz ',correo:'ad88dv@gmail.com',password:'03PFCMX14260'},
    {nombre:'Elisa Vegué Llorente',correo:'vegue.elisa@gmail.com',password:'03PFCES36261'},
    {nombre:'Cynthia Celina Martínez Núñez',correo:'celinamarnu@gmail.com',password:'03PFCMX22262'},
    {nombre:'José Ramón Rosas Jiménez',correo:'ramon1902@live.com.mx',password:'03PFCMX02263'},
    {nombre:'David Viramontes Cocolán',correo:'davidvico12@hotmail.es',password:'03PFCMX19264'},
    {nombre:'Luis Antonio Cerón Aguilar',correo:'luisagilar_arq@outlook.com',password:'03PFCMX28265'},
    {nombre:'Andrés Pastrana Bonillo',correo:'andrespastranabonillo@gmail.com',password:'03PFCES36266'},
    {nombre:'Miguel de Rojas Dierssen',correo:'miguelderojas@live.com',password:'03PFCES36267'},
    {nombre:'Juan Rubén Luna Frías',correo:'jruben.luna13@gmail.com',password:'03PFCMX21268'},
    {nombre:'Regina Kuri Martínez',correo:'r_kuri19@hotmail.com',password:'03PFCMX01269'},
    {nombre:'José Danilo Castro Hernández',correo:'arq.jdch@gmail.com',password:'03PFCMX01271'},
    {nombre:'Sara Castellanos Ruiz ',correo:'sahddi_castellanos@hotmail.com',password:'03PFCMX14272'},
    {nombre:'Miguel Ángel Villicaña Peralta ',correo:'miguevillis@gmail.com',password:'03PFCMX02273'},
    {nombre:'Gianmarco Vidales',correo:'gianmarcovidales@hotmail.com',password:'03PFCMX01274'},
    {nombre:'Sherwin Noé Sanmartín Molina',correo:'sherwinsm@outlook.com',password:'03PFCMX02275'},
    {nombre:'Gerardo Arrieta Pérez',correo:'gerardoarrietaperez@gmail.com',password:'03PFCMX01276'},
    {nombre:'José Antonio Preciado Jiménez ',correo:'ohdude@live.com.mx',password:'03PFCMX14277'},
    {nombre:'Edgar Eduardo Ruiz Chávez ',correo:'edgarruiz_chavez17@outlook.com',password:'03PFCMX02278'},
    {nombre:'Luis Daniel Martínez Téllez',correo:'luis.mtztz@gmail.com',password:'03PFCMX24279'},
    {nombre:'Paulina Astrid Martínez Castillo',correo:'pauastrid.25@gmail.com',password:'03PFCMX01280'},
    {nombre:'Leonardo David Pérez Sánchez',correo:'leo.arq.19@gmail.com',password:'03PFCMX01281'},
    {nombre:'Eduardo Alejandro Baca Rodríguez',correo:'eduardobacarodriguez@gmail.com',password:'03PFCMX02282'},
    {nombre:'Carlos Emmanuel Garcia Del Toro',correo:'arq.charlie@outlook.com',password:'03PFCMX14283'},
    {nombre:'Sara Martínez de Velasco Marín',correo:'sara.mvm@hotmail.com',password:'03PFCES36284'},
    {nombre:'José Daniel Romero Varón',correo:'rovadan@hotmail.com',password:'03PFCMX14285'},
    {nombre:'Antonio de Jesús Huesca Herrera',correo:'arqantoniohuesca@gmail.com',password:'03PFCMX26286'},
    {nombre:'Rosemberg Echeverría Mayorga ',correo:'arq-rosberg18@outlook.com ',password:'03PFCMX31287'},
    {nombre:'Claudio Morales Vergara',correo:'claudiomv1304@gmail.com',password:'03PFCMX01289'},
    {nombre:'Isaías Aldair Cruz Hernández ',correo:'isaiasaldair3@gmail.com',password:'03PFCMX24290'},
    {nombre:'José Guadalupe Panduro Romero',correo:'rooarquitectos@gmail.com',password:'03PFCMX14291'},
    {nombre:'Andrés Salinas Popp',correo:'andres@anexo.mx',password:'03PFCMX01292'},
    {nombre:'Ricardo Alfonso Ortíz Ojeda ',correo:'ricardoalfonso9@hotmail.com',password:'03PFCMX02293'},
    {nombre:'Alberto Almaraz Moreno',correo:'almaraz.aam@gmail.com',password:'03PFCMX28294'},
    {nombre:'Fernando Escobedo García',correo:'garciafernando@live.com',password:'03PFCMX28295'},
    {nombre:'Brian Pillado Pizarro',correo:'brian.pillado@hotmail.com',password:'03PFCMX01296'},
    {nombre:'Damián Jared Salazar Carrejo',correo:'damian_j12@hotmail.com',password:'03PFCMX05297'},
    {nombre:'Itzel Valeria Flores Orozco',correo:'itzelflores.2010@gmail.com',password:'03PFCMX01298'},
    {nombre:'Alessandra Cortes Rodas',correo:'alessa0923@gmail.com',password:'03PFCMX01299'},
    {nombre:'Mónica Meza Pérez',correo:'monmezap@gmail.com',password:'03PFCMX01300'},
    {nombre:'Eduardo Ramírez Domínguez',correo:'eduardo.ram.dom21@gmail.com',password:'03PFCMX01301'},
    {nombre:'Jorge Alberto Carballo Rodríguez',correo:'jorgecarb95@gmail.com',password:'03PFCMX26302'},
    {nombre:'Oscar Sameer Nava Castillo',correo:'sameer.nava88@gmail.com',password:'03PFCMX01303'},
    {nombre:'Valeria Martínez Sada',correo:'sadavale9@gmail.com',password:'03PFCMX03304'},
    {nombre:'Mariana Gutiérrez Terán',correo:'mariana_gtz.teran98@hotmail.com',password:'03PFCMX27305'},
    {nombre:'Rodrigo Becerra',correo:'rodrigobecerra@redestudio.mx',password:'03PFCMX01306'},
    {nombre:'Ana Karen Soria Jiménez',correo:'annsoria89@gmail.com',password:'03PFCMX01307'},
    {nombre:'Andrea Monserrat Merizalde Escutia',correo:'a.merizalde.e@gmail.com',password:'03PFCMX06308'},
    {nombre:'Erik Mauricio Ornelas Gutiérrez',correo:'erikmauornelas@gmail.com',password:'03PFCMX14309'},
    {nombre:'Carlos Andrés Galindo Gómez',correo:'gogacnd@gmail.com',password:'03PFCMX14310'},
    {nombre:'Axel Kevin Pérez Solana',correo:'arkxel91@gmail.com',password:'03PFCMX01311'},
    {nombre:'Sofia Ghigliazza Lieberman',correo:'sofiaghigliazza@gmail.com',password:'03PFCMX01313'},
    {nombre:'Paula Alonso Velázquez',correo:'paula.alonsovel@gmmail.com',password:'03PFCMX01314'},
    {nombre:'Dulce Villegas',correo:'arch.fmar@gmail.com',password:'03PFCMX01315'},
    {nombre:'Ana Sabater Royo',correo:'asabro_ana@hotmail.com',password:'03PFCES36316'},
    {nombre:'Luis Eduardo Garcia Garrido',correo:'eduardo.gar.garr@gmail.com',password:'03PFCMX14317'},
    {nombre:'Daniel Rosales Mora',correo:'danielrosalesmora@hotmail.com',password:'03PFCMX14318'},
    {nombre:'Edwin Eduardo González Aguilar',correo:'edwin.gonzalezar@udlap.mx',password:'03PFCMX28319'},
    {nombre:'Cecilia Valdés Iñigo ',correo:'cvaldes_96@hotmail.com',password:'03PFCMX02320'},
    {nombre:'Alfredo Vargas Moreno ',correo:'alfredovargas.arq@gmail.com',password:'03PFCMX27321'},
    {nombre:'Dalia Lizeth Salazar Ríos ',correo:'lizethsrios@gmail.com',password:'03PFCMX01322'},
    {nombre:'Jessica Nallely Domínguez Crescencio ',correo:'nayeoned@gmail.com ',password:'03PFCMX02323'},
    {nombre:'Ignacio Quiroz González',correo:'ignacioquirozglz@hotmail.com',password:'03PFCMX05324'},
    {nombre:'Fernando Gallegos López ',correo:'arqfernando.tm@gmail.com',password:'03PFCMX01325'},
    {nombre:'Mariangela GG',correo:'mariangelaggu@gmail.com',password:'03PFCMX01326'},
    {nombre:'Mariana Arely Villafán Flores',correo:'mariana.cela@gmail.com',password:'03PFCMX01327'},
    {nombre:'Rebeca García Julio',correo:'gjulio.rebeca@gmail.com',password:'03PFCMX01328'},
    {nombre:'Eduardo Morales Castellanos',correo:'eduardomorales.castellanos@gmail.com',password:'03PFCMX35329'},
    {nombre:'José Aurelio Espinoza Moreno',correo:'arq.ae.mx@gmail.com',password:'03PFCMX27359'},
    {nombre:'Eduardo Benitez Chavira',correo:'e.be.chavira@gmail.com',password:'03PFCMX01312'},
    {nombre:'Enrique Franco Paquot',correo:'francopaquott@gmail.com',password:'03PFCMX11333'},
    {nombre:'Aleksander Cruz Silva',correo:'aleksandercruzsilva@gmail.com',password:'03PFCMX01334'},
    {nombre:'Diego Mateos',correo:'diego-mateos@live.com',password:'03PFCMX01335'},
    {nombre:'Jose Emmanuel Frias Muñoz',correo:'josefri12@hotmail.com',password:'03PFCMX22337'},
    {nombre:'Pedro Alexander Mendoza Avila',correo:'mendoza.avila.pedro@gmail.com',password:'03PFCPE36339'},
    {nombre:'Ernesto Mota Tovar',correo:'motaark@gmail.com',password:'03PFCMX22340'},
    {nombre:'Irving Mauricio Estrada Castro',correo:'i.estradaarch@gmail.com',password:'03PFCMX30341'},
    {nombre:'Rubén Martínez Bermúdez',correo:'scalearquitectos@outlook.com',password:'03PFCMX01343'},
    {nombre:'Roger de Jesús Méndez Vázquez',correo:'rmendez.09@hotmail.com',password:'03PFCMX31344'},
    {nombre:'Daniel González Chibli',correo:'danygonzalezchibli@gmail.com',password:'03PFCMX28345'},
    {nombre:' Jacobo Octavio Arvizu Hernández',correo:'jacoarvizu@gmail.com',password:'03PFCMX01346'},
    {nombre:'Carlos Rafael Dubois Casillas',correo:'archi.9@hotmail.com',password:'03PFCMX14347'},
    {nombre:'Alejandro Caraballo Llorente',correo:'alexcaraballorente@gmail.com',password:'03PFCES36349'},
    {nombre:'Reynaldo Malagon Mendoza',correo:'malagon.arquitectura@gmail.com',password:'03PFCMX06351'},
    {nombre:'Jorge Alejandro Loredo Serrano ',correo:'17alejandroloredo@gmail.com',password:'03PFCMX24352'},
    {nombre:'Javier Dabague Herrejón',correo:'dhjavier49@gmail.com',password:'03PFCMX26353'},
    {nombre:'Harry Skipsey',correo:'haskar93@gmail.com',password:'03PFCMX01354'},
    {nombre:'Omar Ramirez Tenorio',correo:'omarr510@gmail.com',password:'03PFCMX26355'},
    {nombre:'Mariana Espinosa Durante',correo:'e-mariana@outloook.com',password:'03PFCMX26357'},
    {nombre:'Cristina Rodríguez García',correo:'crgcricri@gmail.com',password:'03PFCES36358'},
    {nombre:'Arturo Andrade Azcona',correo:'info@a3amx.com',password:'03PFCMX02360'},
    {nombre:'Enrique Vega Vega',correo:'enriquevgvg@gmail.com',password:'03PFCMX06361'},
    {nombre:'Diana Mayo Garcia',correo:'diana_mayog@hotmail.com',password:'03PFCMX26362'},
    {nombre:'Martha Horeb Ruiz Acosta',correo:'horeb.1706@hotmail.com',password:'03PFCMX26363'},
    {nombre:'Tamara Paulina Vega Galicia ',correo:'tamaravega15@yahoo.com.mx',password:'03PFCMX01364'},
    {nombre:'Oscar Antonio Miranda Armenta',correo:'oscarmiranda123abc@hotmail.com',password:'03PFCMX26365'},
    {nombre:'Natalia Alarcón Cuevas',correo:'nataliaac11@outlook.com',password:'03PFCMX26366'},
    {nombre:'Stephany Paola Nevárez Reza ',correo:'spaolanevarezr@gmail.com',password:'03PFCMX08370'},
    {nombre:'Abraham Buenrostro',correo:'b.enrostrov@gmail.com',password:'03PFCMX01372'},
    {nombre:'Victor Ivan Cristóbal Martínez ',correo:'victorcristobal06@gmail.com',password:'03PFCMX26373'},
    {nombre:'Paola Lorenzo Solana',correo:'paola@sucarrats-lorenzo.com',password:'03PFCMX01374'},
    {nombre:'Melanie Azucena Millán Acosta ',correo:'A01272457@itesm.mx',password:'03PFCMX06375'},
    {nombre:'Emir Rodrigo Castañeda López',correo:'rodrigo.castaneda@gracsa.co',password:'03PFCMX01376'},
    {nombre:' Karla Alvarado Herrera',correo:'karla.alvarado96@gmail.com',password:'03PFCMX02378'},
    {nombre:'Raúl Ricardo Martínez Sánchez ',correo:'ricardo@rxy.com.mx',password:'03PFCMX01383'},
    {nombre:'David Antonio Gómez Sánchez ',correo:'davesanchez16@live.com',password:'03PFCMX28384'},
    {nombre:'Ricardo Mouret Abadiano',correo:'rma_9421@hotmail.com',password:'03PFCMX02386'},
    {nombre:'Maite Garcia-Lascurain',correo:'mteglmx@gmail.com',password:'03PFCMX01387'},
    {nombre:'Rodrigo Saavedra Pérez Salas',correo:'ro@saavedraarquitectos.com',password:'03PFCMX01388'},
    {nombre:'Julio Cesar Bueno Robles',correo:'juliobuenoarq@gmail.com',password:'03PFCMX01389'},
    {nombre:'Luis Alberto Rosas Gómez',correo:'luisrosasg93@gmail.com',password:'03PFCMX35390'},
    {nombre:'Juan José Corona Lucio',correo:'jjcoronalucio@gmail.com',password:'03PFCMX01391'},
    {nombre:'Marcela Alejandra Vazquez López',correo:'marcelavzqzlpz@gmail.com',password:'03PFCMX01393'},
    {nombre:'Macarena Alejandra Troncoso Delfin',correo:'matroncoso@uc.cl',password:'03PFCCH36394'},
    {nombre:'Ana Laura Padilla Couto',correo:'anapc020@gmail.com',password:'03PFCMX01396'},
    {nombre:'Jacobo Linder Cohen',correo:'jaco.linderco@hotmail.com',password:'03PFCMX01397'},
    {nombre:'Sara Isabel Jiménez Arellano',correo:'saraisabel2912@gmail.com',password:'03PFCMX26398'},
    {nombre:'José Luis Domínguez Rodríguez',correo:'joseluis.d97@gmail.com',password:'03PFCMX03399'},
    {nombre:'Jessica Pamela Park Zavala',correo:'jessicaparkz@hotmail.com',password:'03PFCMX20400'},
    {nombre:'Marianee Guendulain Ruiz',correo:'marianee.gr@gmail.com',password:'03PFCMX01401'},
    {nombre:'Miguel Ángel Dóñez García',correo:'mangeld14@gmail.com',password:'03PFCMX03402'},
    {nombre:'Oswaldo Delgado Jiménez',correo:'oswaldoydelgado@gmail.com',password:'03PFCMX14404'},
    {nombre:'Christian Muñoz Escobedo',correo:'christianescobedo9@outlook.com',password:'03PFCMX22405'},
    {nombre:'Eduardo Arturo García Ortega',correo:'eago96@hotmail.com',password:'03PFCMX26406'},
    {nombre:'Oberlin Omar Tamez Reyna',correo:'oberlin_t@hotmail.com',password:'03PFCMX15407'},
    {nombre:'Abril Rueda',correo:'abril.rueda@gmail.mx',password:'03PFCMX01409'},
    {nombre:'Martín Solis Alarcon',correo:'sonicdx224@hotmail.com',password:'03PFCMX01410'},
    {nombre:'Mariana Stephanie Cruz Zapata',correo:'toc.informacion@gmail.com',password:'03PFCMX27412'},
    {nombre:'Ana Marcela Cuevas Vidal',correo:'anacuevasvidal@gmail.com',password:'03PFCMX26413'},
    {nombre:'Dalila Noemi Rodriguez Alfaro',correo:'dali_rodalf@hotmail.com',password:'03PFCMX19414'},
    {nombre:'Elioenai Jiménez Castellanos ',correo:'realred23@hotmail.com',password:'03PFCMX19416'},
    {nombre:'Bruno Miguel Zarrabe Ricoy',correo:'b.zarrabe@gmail.com',password:'03PFCMX01417'},
    {nombre:'David Rios Aguirre',correo:'arqdriosag@gmail.com',password:'03PFCMX21418'},
    {nombre:'Luis Guillermo García Rugerio',correo:'rugerio.luisg@gmail.com',password:'03PFCMX03419'},
    {nombre:'Tania cristina Nevarez calderon',correo:' a.nevareztc@gmail.com',password:'03PFCEU36420'},
    {nombre:'Isi Abigail Cruz Medina ',correo:'abigail_cruz30@outlook.com',password:'03PFCMX01421'},
    {nombre:'José Francisco Uribe Rodríguez ',correo:'pacorodriguez2008@gmail.com',password:'03PFCMX01422'},
    ];

  constructor(private auth: AuthService, private afs: AngularFirestore) {
    this.itemsCollection = afs.collection<Item>( 'archivos');
    
    this.items = this.itemsCollection.valueChanges();
    console.log(this.participantes);

    

   }

  ngOnInit() {
  }

  getFormatoArchivo(nombreArchivo: string): string {
    const pos = nombreArchivo.indexOf('.');

    const formato = nombreArchivo.substring(pos+1, nombreArchivo.length);

    return formato;
  }

}
